parameters:
  terramar.customer.helper.customer.class:           TerraMar\Bundle\CustomerBundle\Helper\CustomerHelper
  terramar.customer.helper.email_verification.class: TerraMar\Bundle\CustomerBundle\Helper\EmailVerificationHelper
  terramar.customer.helper.search_results.class:     TerraMar\Bundle\CustomerBundle\Helper\SearchResultsHelper
  terramar.customer.helper.export.class:             TerraMar\Bundle\CustomerBundle\Helper\ExportHelper
  terramar.customer.factory.customer.class:          TerraMar\Bundle\CustomerBundle\Factory\CustomerFactory

services:
  # Helpers
  terramar.customer.helper.customer:
    class: %terramar.customer.helper.customer.class%
  terramar.customer.helper.email_verification:
    class: %terramar.customer.helper.email_verification.class%
  terramar.customer.helper.search_results:
    class: %terramar.customer.helper.search_results.class%
    arguments: [ @session ]
  terramar.customer.helper.export:
    class: %terramar.customer.helper.export.class%

  # Factories
  terramar.customer.factory.customer:
    class: %terramar.customer.factory.customer.class%

  # Subscribers and Listeners
  terramar.customer.subscriber.user_accountability:
    public: false
    class: TerraMar\Bundle\CustomerBundle\Subscriber\UserAccountabilitySubscriber
    arguments: [ @service_container ]
    tags:
      - { name: doctrine.event_subscriber }
  terramar.customer.subscriber.email_verification:
    public: false
    class: TerraMar\Bundle\CustomerBundle\Subscriber\EmailVerificationSubscriber
    arguments: [ @service_container ]
    tags:
      - { name: doctrine.event_subscriber }
